/* biome-ignore-all lint/security/noDangerouslySetInnerHtml: trusted HTML generated by shiki */
import { codeToHtml } from "shiki";
import { cn } from "@/lib/cn";

export interface CodeBlockProps {
  code: string;
  lang?: string;
  fileName?: string;
  className?: string;
}

export async function CodeBlock({
  code,
  lang = "javascript",
  fileName = "calculate.js",
  className,
}: CodeBlockProps) {
  const highlighted = await codeToHtml(code, {
    lang,
    theme: "vesper",
  });

  const highlightedNode = (
    <div
      className="codeblock-shiki overflow-x-auto"
      dangerouslySetInnerHTML={{ __html: highlighted }}
    />
  );

  return (
    <section
      className={cn(
        "w-full max-w-[560px] border border-border-primary bg-bg-elevated",
        className,
      )}
    >
      <header className="flex h-10 items-center gap-3 border-b border-border-primary px-4">
        <span className="size-2.5 rounded-full bg-accent-red" />
        <span className="size-2.5 rounded-full bg-accent-amber" />
        <span className="size-2.5 rounded-full bg-accent-green" />
        <span className="flex-1" />
        <span className="text-xs text-text-tertiary">{fileName}</span>
      </header>

      {highlightedNode}
    </section>
  );
}
